baseURL = "/"
languageCode = "en-us"
title = "Y.CH.Y"
theme = "PaperMod"
copyright = "Y.CH.Y"
disqusShortname = "example"
googleAnalytics = "G-X1L70M4MM0"

# Main menu
[[menu.main]]
name = "首页"
url = "/"
weight = 2


[markup]
[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 1
[markup.highlight]
style = "dracula"
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
# PaperMod specific settings
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

# Your existing settings
mainSections = ["posts"]
description = ""
dateFormat = "2006 Jan 02"

# Custom CSS
assets = { css = ["css/custom.css"] }

# Home page settings
homeInfoParams = { Title = "Y.CH.Y"}

socialIcons = [
    # Add your social icons here, for example:
    # { name = "github", url = "https://github.com/yourusername" }
]

[params.cover]
linkFullImages = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]